§FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# monocle

API для получения радиолокационных данных. Все комментарии на русском, в соответствии со спецификацией. В именах сущностей часть названий, для которых удалось подобрать соотвествующий англоязычный аналог, передена на английский, часть оставлена в виде аббревиатур, соответсвующих русскоязычным аббревиатурам.

## АС СМРЛП [/station/list{?ids}{?title}{?limit}{?offset}]

Запрос состава АС СМРЛП и параметров отдельных постов

### Получить список СМРЛП [GET]

+ Parameters
    * ids - Фильтр по id
    + title - Фильтр по названию
    + limit - Количество строк на странице
    + offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 5,
            "items": [
                {
                    "id": 1,
                    "index": "0001",
                    "title": "Орловка",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": 1,
                        "title": "Обзор 50 км УМ 0-90°"
                    },
                    "schedule_started": true,
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 2,
                    "index": "0002",
                    "title": "Чкаловский",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "coldsea",
                    "current_program": {
                        "id": 1,
                        "title": "Обзор 50 км УМ 0-90°"
                    },
                    "schedule_started": true,
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": "PT0H12M0S",
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 3,
                    "index": "0003",
                    "title": "Елец",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "MASL": 0,
                    "HAAT_radar": 0,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_started": false,
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 4,
                    "index": "0004",
                    "title": "Тула",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "MASL": 0,
                    "HAAT_radar": 1,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "warmsea",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_started": false,
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                },
                {
                    "id": 5,
                    "index": "0005",
                    "title": "Щелково",
                    "latitude": 55.807775,
                    "longitude": 37.566814,
                    "MASL": 0,
                    "HAAT_radar": 1,
                    "HAAT_AMS_DAD": 0,
                    "terrain_type": "land",
                    "current_program": {
                        "id": 1,
                        "title": "Готовность"
                    },
                    "schedule_started": false,
                    "alarm_id": 0,
                    "record_local_reflection_map_duration": null,
                    "equipment_status": true,
                    "exchange_status": true,
                    "rotation_status": 60
                }
            ]
        }

## СМРЛП [/station/{id}]

Параметры отдельного СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить параметры СМРЛП [GET]

+ Response 200 (application/json)

            {
                "id": 3,
                "index": "0003",
                "title": "Елец",
                "latitude": 55.807775,
                "longitude": 37.566814,
                "MASL": 0,
                "HAAT_radar": 0,
                "HAAT_AMS_DAD": 0,
                "terrain_type": "",
                "current_program": {
                    "id": 1,
                    "title": "Готовность"
                },
                "schedule_status": "started",
                "alarm_id": 0,
                "record_local_reflection_map_duration": null,
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
            
+ Response 404

### Обновить параметры СМРЛП [PUT]

+ Request (application/json)

        {
            "id": 3,
            "index": "0003",
            "title": "Елец",
            "latitude": 55.807775,
            "longitude": 37.566814,
            "MASL": 0,
            "HAAT_radar": 0,
            "HAAT_AMS_DAD": 0,
            "terrain_type": "land",
            "alarm_id": 0
        }

+ Response 422 (application/json)

    + Body

            {
                "index": "Невалидное значение",
                "index_not_unique": "Индекс не уникален",
                "title": "Невалидное значение",
                "terrainType": "Невалидное значение",
                "latitude": "Невалидное значение",
                "longitude": "Невалидное значение",
                "MASL": "Невалидное значение",
                "HAAT_radar": "Невалидное значение",
                "HAAT_AMS_DAD": "Невалидное значение",
                "alarm_id": "Невалидное значение"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 3
                "index": "0003",
                "title": "Елец",
                "latitude": 55.807775,
                "longitude": 37.566814,
                "MASL": 0,
                "HAAT_radar": 0,
                "HAAT_AMS_DAD": 0,
                "terrain_type": "land",
                "alarm_id": 0,
                "record_local_reflection_map_duration": null,
                "equipment_status": true,
                "exchange_status": true,
                "rotation_status": 60
            }
        
+ Response 404

## Справочник типов РЛП [/station/{id}/types/rlp_list]

Cправочник типов РЛП для СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить перечень типов РЛП [GET]

+ Response 200 (application/json)

        {
            "count": 12,
            "items": [{
                    "id": 0,
                    "index": "Wpcell",
                    "title": "Карта метео явлений (в ячейках)",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 1,
                    "index": "Wpfig",
                    "title": "Карта метео явлений (в контурах)",
                    "enable_altitude_scale": true,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 2,
                    "index": "Htmax",
                    "title": "Карта верхней границы радиоэха",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": false
                },
                {
                    "id": 3,
                    "index": "Htmin",
                    "title": "Карта нижней границы радиоэха",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 4,
                    "index": "VvField",
                    "title": "Карта векторного поля скоростей",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 5,
                    "index": "WindShiftH",
                    "title": "Объемная карта значений горизонтального сдвига ветра",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 6,
                    "index": "WindShiftV",
                    "title": "Объемная карта значений вертикального сдвига ветра",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 7,
                    "index": "VIL",
                    "title": "Карта интегрированного водозапаса в ячейках, кг/м^2",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 8,
                    "index": "RflS3",
                    "title": "Количество осадков накопленное за 3, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 9,
                    "index": "RflS6",
                    "title": "Количество осадков накопленное за 6, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 10,
                    "index": "RflS12",
                    "title": "Количество осадков накопленное за 12, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                },
                {
                    "id": 11,
                    "index": "RflS24",
                    "title": "Количество осадков накопленное за 24, мм/ч",
                    "enable_altitude_scale": false,
                    "mixed_with_other_rlp": true
                }
            ]
        }

## Справочник типов КС [/station/{id}/types/сs_list]

Cправочник типов конических сечений для СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить перечень типов КС [GET]

+ Response 200 (application/json)

        {
            "count": 5,
            "items": [{
                    "id": 0,
                    "index": "Dbz",
                    "title": "Отражаемость"
                },
                {
                    "id": 1,
                    "index": "Vr",
                    "title": "Радиальная скорость"
                },
                {
                    "id": 2,
                    "index": "Edr",
                    "title": "Уд. скорость диссипации турбулентной энергии"
                },
                {
                    "id": 3,
                    "index": "RflI",
                    "title": "интенсивность осадков"
                },
                {
                    "id": 4,
                    "index": "Power",
                    "title": "Мощность"
                }
            ]
        }


## Минимально опасное метеоявление СМРЛП [/station/{id}/settings/min_dangerous_meteo]

Текущий уровень опасного метеоявления, используется для индикации/уведомлений

+ Parameters
    + id (number) - ID СМРЛП

### Получить [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "title": "Слоистая облачность"
        }

## Настройки СМРЛП [/station/{id}/settings]

Настройки отдельного СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить настройки СМРЛП [GET]

+ Response 200 (application/json)

            {
                "id": 3,
                "title": "Елец", 
                "antenna": {
                    // Номера канала излучения излучения
                    "channel_id": 2,
                    // Азимут
                    "azimuth": 60,
                    // Угол места
                    "tilt": 16
                },
                "calibration": {
                    // Поправка на север
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_radial_velocity",
                    "manual_param": "isotherm_height",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_criterion": {
                    // Минимально опасное метеоявление
                    "min_dangerous_meteo": "id": 1,
                    // Период актуализации нулевой изотермы
                    "isotherm_expire_period": 12,
                    // Критерии классификации типов метеоявлений
                    "meteo_options": 
                    {
                        "count": 2,
                        "items":
                        [
                            {
                                // Индекс МЯ
                                "id": 0, 
                                // Наименование МЯ
                                "type": "Облачность (слоистообразная облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    // Индекс параметра
                                    "index": 0,
                                    // Код параметра
                                    "code": "Cl_dBZ23_min",
                                    // Наименование параметра
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z2 и Z3",
                                    // Единицы измерения параметра
                                    "measurement unit": "dBZ"
                                    // Значение параметра для теплого периода
                                    "warm": 10,
                                    // Значение параметра для холодного периода
                                    "cold": -10, 
                                    // Код параметра
                                    "service_life": "All" // (Warm, Cold, All)
                                }
                                ]
                            },
                            {
                                "id": 1, 
                                "type": "Облачность (кучевая облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement unit": "dBZ"
                                    "service_life": "All"
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement unit": "dBZ"
                                    "warm": 35,
                                    "cold": 30,
                                    "service_life": "All"
                                }
                                ]
                            }
                        ]
                    }
                }
            }
            
### Обновить настройки СМРЛП [PUT]

+ Request (application/json)

        {
                "id": 3,
                "antenna": {
                    "channel_id": 2,
                    "azimuth": 60,
                    "tilt": 16
                },
                "calibration": {
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_center_mass",
                    "manual_param": "ground_temperature",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_criterion": {
                    "min_dangerous_meteo_id": 1,
                    "isotherm_expire_period": 12,
                    "meteo_options": 
                    {
                        "count": 2,
                        "items":
                        [
                            {
                                // Индекс МЯ
                                "id": 0, 
                                // Наименование МЯ
                                "type": "Облачность (слоистообразная облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    // Индекс параметра
                                    "index": 0,
                                    // Код параметра
                                    "code": "Cl_dBZ23_min",
                                    // Наименование параметра
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z2 и Z3",
                                    // Единицы измерения параметра
                                    "measurement unit": "dBZ"
                                    // Значение параметра для теплого периода
                                    "warm": 10,
                                    // Значение параметра для холодного периода
                                    "cold": -10, 
                                    // Код параметра
                                    "service_life": "All" // (Warm, Cold, All)
                                }
                                ]
                            },
                            {
                                "id": 1, 
                                "type": "Облачность (кучевая облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement unit": "dBZ"
                                    "service_life": "All"
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement unit": "dBZ"
                                    "warm": 35,
                                    "cold": 30,
                                    "service_life": "All"
                                }
                                ]
                            }
                        ]
                    }
                }
            }

+ Response 422

        {
            "antenna": {
                "channel": "Невалидное значение",
                "azimuth": "Невалидное значение",
                "tilt": "Невалидное значение"
            },
            "calibration": {
                "azimuth_north_fix": "Невалидное значение",
                "cloud_velocity": "Невалидное значение",
                "manual_param": "Невалидное значение",
                "get_auto_param": "Невалидное значение",
                "temperature": "Невалидное значение",
                "period": "Невалидное значение",
                "isotherm0_height": "Невалидное значение",
                "isotherm22_height": "Невалидное значение",
                "tropopause_height": "Невалидное значение"
            },
            "meteo_criterion": {
                "min_dangerous_meteo": "Невалидное значение",
                "isotherm_expire_period": "Невалидное значение",
                "meteo_options": 
                    {
                        "count": 1,
                        "items":
                        [
                            {
                                "id": 0, 
                                "count": 1,
                                "items":
                                [
                                {
                                    "index": 0,
                                    "warm": "Невалидное значение",
                                    "cold": "Невалидное значение", 
                                }
                                ]
                            }
                        ]
                    }
            }
        }

+ Response 200 (application/json)

            {
                "id": 3,
                "title": "Елец",
                "antenna": {
                    "channel": {
                        "id": 2
                    },
                    "azimuth": 60,
                    "tilt": 16
                },
                "calibration": {
                    "azimuth_north_fix": 0,
                    "cloud_velocity": "by_center_mass",
                    "manual_param": "isotherm_height",
                    "get_auto_param": true,
                    "temperature": 1.3,
                    "period": "warm",
                    "isotherm0_height": 200,
                    "isotherm22_height": 3,
                    "tropopause_height": 12000
                },
                "meteo_settings": {
                    "min_dangerous_meteo_id": 1,
                    "isotherm_expire_period": 12,
                    "meteo_options": 
                    {
                        "count": 2,
                        "items":
                        [
                            {
                                // Индекс МЯ
                                "id": 0, 
                                // Наименование МЯ
                                "type": "Облачность (слоистообразная облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    // Индекс параметра
                                    "index": 0,
                                    // Код параметра
                                    "code": "Cl_dBZ23_min",
                                    // Наименование параметра
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z2 и Z3",
                                    // Единицы измерения параметра
                                    "measurement unit": "dBZ"
                                    // Значение параметра для теплого периода
                                    "warm": 10,
                                    // Значение параметра для холодного периода
                                    "cold": -10, 
                                    // Код параметра
                                    "service_life": "All" // (Warm, Cold, All)
                                }
                                ]
                            },
                            {
                                "id": 1, 
                                "type": "Облачность (кучевая облачность)",
                                "count": 1,
                                "items":
                                [
                                {
                                    "index": 0,
                                    "code": "Cl_dBZ2_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                                    "measurement unit": "dBZ"
                                    "service_life": "All"
                                },
                                {
                                    "index": 1,
                                    "code": "Cl_dBZ3_min",
                                    "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                                    "measurement unit": "dBZ"
                                    "warm": 35,
                                    "cold": 30,
                                    "service_life": "All"
                                }
                                ]
                            }
                        ]
                    }
                }
            }
            
+ Response 409

+ Response 404

## Расписание СМРЛП [/station/{id}/schedule]

Работа с расписанием работы отдельного СМРЛП

+ Parameters
    + id (number) - ID СМРЛП

### Получить расписание СМРЛП [GET]

+ Response 200 (application/json)

            {
                "count": 2,
                "items": 
                    [
                        {
                            "id": 1,
                            "program": {
                                "id": 2,
                                "title": "Обзор 50 км УМ 0-90°",
                                "duration": "PT0H10M0S"
                            },
                            "start": "20050809T183142"
                        },
                        {
                            "id": 2,
                            "program": {
                                "id": 3,
                                "title": "Сектор 50 км 60-30°",
                                "duration": "PT0H12M0S"
                            },
                            "start": "20050809T183142"
                        }
                    ]
            }
+ Response 409

### Обновить расписание СМРЛП [PUT]

+ Request (application/json)

        [
            {
                "id": 1,
                "program_id": 2,
                "start": "20050809T183142"
            },
            {
                "id": 2,
                "program_id": 3,
                "start": "20050809T183142"
            }
        ]

+ Response 200 (application/json)

            {
                "count": 5,
                "items":
                    [
                        {
                            "id": 1,
                            "program": {
                                "id": 2,
                                "title": "Обзор 50 км УМ 0-90°",
                                "duration": "PT0H10M0S"
                            },
                            "start": "20050809T183142"
                        },
                        {
                            "id": 2,
                            "program": {
                                "id": 3,
                                "title": "Сектор 50 км 60-30°",
                                "duration": "PT0H12M0S"
                            },
                            "start": "20050809T183142"
                        }
                    ]
            }

+ Response 422

        [
            {
                "index": 0,
                "start": "Программа полностью не выполняется. Измените время начала или поменяйте программу."
            },
            {
                "index": 1,
                "program_id": "Указанная программа не найдена."
            }
        ]

+ Response 409

+ Response 404

## Включить работу СМРЛП по расписанию [/station/{id}/schedule/start]

Запуск работы СМРЛП по предварительно заданному расписанию

+ Parameters
    + id (number) - ID СМРЛП

### Включить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Остановить работу СМРЛП по расписанию [/station/{id}/schedule/stop]

Отмена работы СМРЛП по заданному расписанию и перевод РЛС в режим "ГОТОВНОСТЬ"

+ Parameters
    + id (number) - ID СМРЛП

### Остановить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404


## Запустить запись карты местных отражений [/station/{id}/local_reflection_map/start{?cycle}]

Запуск построения карты местных отражений

+ Parameters
    + id (number) - ID СМРЛП
    * cycle - количество циклов, в текущей итерации всегда 1

### Запись карты местных отражений [POST]

+ Response 200 (application/json)

            {
                "record_local_reflection_map_duration": "PT0H12M0S"
            }

+ Response 409

+ Response 404

## Остановить запись карты местных отражений [/station/{id}/local_reflection_map/stop]

Отмена запущенного процесса записи карты местных отражений

+ Parameters
    + id (number) - ID станции
    
### Остановить запись карты местных отражений [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Запустить работу СМРЛП по программе [/station/{id}/program/{program_id}/start]

Запуск работы СМРЛП по указанной программе

+ Parameters
    + id (number) - ID СМРЛП
    + program_id (number) - ID программы

### Запустить [POST]

+ Response 200 (application/json)

            {
                "id": 2,
                "title": "Сектор 50 км 60-30°",
                "duration": "PT0H12M0S",
                "mode": "sector",
                "distance": 50,
                "elevation_change_azimuth": 0,
                "left_border_azimuth": 0,
                "right_border_azimuth": 0,
                "elevation_program": [{
                  "value": 1
                }],
                "blocking_program": [
                  {
                    "start": 0,
                    "end": 0
                  }
                ]
            }

+ Response 409

+ Response 404

## Остановить работу СМРЛП по программе [/station/{id}/program/stop]

Отмена работы СМРЛП по текущей программе и перевод РЛС в режим "ГОТОВНОСТЬ"
Примечание: для отмены работы по расписанию используется другой метод

+ Parameters
    + id (number) - ID СМРЛП

### Остановить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Запуск программы "КОНТРОЛЬ" для РЛС СМРЛП [/station/{id}/check/start]

Запуск встроенного контроля РЛС (особая программа)

+ Parameters
    + id (number) - ID СМРЛП

### Запустить [POST]

+ Response 200 (application/json)

+ Response 409

+ Response 404

## Данные метео [/station/{id}/nams_data]

Получение данных от метедатчиков СМРЛП (сортированные)

+ Parameters
    + id (number) - ID СМРЛП

### Получить [GET]

+ Response 200 (application/json)

        {
            "date": "2018-01-30T23:59:55+00:00",
            "humidity": "0",
            "pressure": "95120",
            "wind_azimuth": "29",
            "wind_speed": "2",
            "temp": "-34.5"
        }

## Получение данных метеостатистики [/station/{id}/meteo_stat{?from}{?to}]

Получение данных метеостатистики для обзоров (сортированные)

+ Parameters
    + id (number) - ID СМРЛП
    * from - Начальный период поиска (если не указан, то возвращается последняя метеостатистика)
    * to - Конечный период поиска (если не указан, то возвращается последняя метеостатистика)

### Получить [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": [
                {
                    // скорость перемещения облачных облазований
                    "velocityMOAbs": 25,
                    // направление перемещения облачных облазований
                    "velocityMOAz": 110,
                    // максимальная верхняя граница облачности
                    "altitudeMaxMO": 5600,
                    // минимальная нижняя граница радиоэха
                    "altitudeMinRefl": 700,
                    // максимальный сдвиг ветра горизонтальный
                    "maxWSh": 198.096,
                    // минимальнай сдвиг ветра горизонтальный
                    "minWSh": 0.0367296,
                    // максимальный сдвиг ветра верт.
                    "maxWSv": 0,
                    // минимальнай сдвиг ветра верт.
                    "minWSv": 1.79769e+308,
                    // максимальная турбулентность
                    "maxEDR": 0,
                    // минимальная турбулентность
                    "minEDR": 0,
                    // максимальная интенсинвность приземных осадков
                    "maxGroundRflI": 4.72745,
                    // минимальная интенсинвность приземных осадков
                    "minGroundRflI": 0.00308279,
                    // максимальный класс метеоявлений
                    "maxWeatherClass": 12,
                    // минимальный класс метеоявлений
                    "minWeatherClass": 1,
                    // множество обнаруженных МЯ с АВТОсортировкой значений по возрастанию
                    "wpset": [
                        1,
                        6,
                        9,
                        12
                    ],
                    "date": "2018-01-30T17:25:52+00:00"
                },
                {
                    "velocityMOAbs": 20,
                    "velocityMOAz": 100,
                    "altitudeMaxMO": 5700,
                    "altitudeMinRefl": 600,
                    "maxWSh": 271.809,
                    "minWSh": 0.0370822,
                    "maxWSv": 0,
                    "minWSv": 1.79769e+308,
                    "maxEDR": 0,
                    "minEDR": 0,
                    "maxGroundRflI": 5.03446,
                    "minGroundRflI": 0.00308279,
                    "maxWeatherClass": 12,
                    "minWeatherClass": 1,
                    "wpset": [
                        1,
                        6,
                        9,
                        12
                    ],
                    "date": "2018-01-30T17:30:46+00:00"
                }
            ]
        }

## Список архивных обзоров [/station/{id}/archive_product_list]

Общий для РЛП и КС (сортированный)

+ Parameters
    + id (number) - ID радара

### Получить [GET]

+ Response 200 (application/json)

        {
            "count": 10,
            "items": [
                {"date": "2018-01-30T17-25-52"},
                {"date": "2018-01-30T17-30-46"},
                {"date": "2018-01-30T17-35-49"},
                {"date": "2018-01-30T17-40-54"},
                {"date": "2018-01-30T17-45-58"},
                {"date": "2018-01-30T17-51-01"},
                {"date": "2018-01-30T17-56-02"}
            ]
        }

## Получение карт РЛП [/station/{id}/rlp/{type}/{?rlp_id}{?only_dangerous}{?altitude}{?date}{?cell_size}{?radius}]

Получение карт РЛП для обзоров (сортированные)

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + type (str) - тип данных, для данной итерации всегда png
    * rlp_id - id радиолокационного продукта
    * only_dangerous - отображать только ОМЯ [True/False]
    * altitude - Высота в метрах [100:20000]
    * date - Дата обзора (если не указан, то возвращается последнее РЛП)
    * cell_size - Размер области, которую покрывает 1 пиксель в м., в текущей итерации всегда 1000
    * radius - Радиус обзора в км., в текущей итерации всегда 100

+ Response 200 (application/json)

        {
            "date": "2018-01-30T17:25:52+00:00",
            "type": "png",
            "params": {
                // [100:100]
                "radius": 100, 
                // [100:1000]
                "pixel_size": 1000,
                // [200:200]
                "image_size": 200
            },
            "url": "/rlp/0/?img=monocle-autodor-node-001_2018-01-30_17-25-52_map-htmax-1e+02-1000.png"
        }

## Получение КС [/station/{id}/cs/{?type}/{?cs_id}{?indicator}{?altitude}{?date}{?cell_size}{?radius}{?angle}{?interval}]

Получение конических сечений для обзоров (сортированные)

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + type (str) - тип данных, для данной итерации всегда png
    * cs_id - тип конического сечения 
    * indicator -  CAPPI или PPI
    * altitude - Высота в метрах (только для CAPPI) [100:20000]
    * date - Дата обзора (если не указан, то возвращается последнее КС)
    * cell_size - Размер области, которую покрывает 1 пиксель в м., в текущей итерации всегда 1000
    * radius - Радиус обзора в км., в текущей итерации всегда 100
    * angle (number) - Угол места (градусы) (только для PPI) [0.0:90.0]
    * interval (number) - Интервал построения конических сечений (по высоте) (только для CAPPI) [100:20000]
    

+ Response 200 (application/json)

        {
            "date": "2018-01-30T17:25:52+00:00",
            "type": "png",
            "params": {
                // [100:100]
                "radius": 100,
                // [100:1000]
                "pixel_size": 1000,
                // [200:200]
                "image_size": 200
            },
            "url": "/rlp/0/?img=monocle-autodor-node-001_2018-01-30_17-25-52_cs-dbz-cappi-100-120-1000.png"
        }

+ Response 404

## Метеоинформация в указанной точке [/station/{id}/{product_type}/point/{?product_ids}{?coordinates}]

Получение данных маркера для указанного продукта

### Получить [GET]

+ Parameters
    + id (number) - ID СМРЛП
    + product_type - РЛП или КС
    * product_ids -  Фильтр по id
    * coordinates - Координаты точки
    

+ Response 200 (application/json)

        {
            "atmospheric_process": "Ливень слабый",
            ...
        }
            
## Программы [/program/list{?mode}{?title}{?limit}{?offset}]

Работа по списком программ (для всей АС СМРЛП)

### Получить список программ [GET]

+ Parameters
    * mode - Фильтр режима
    * title - Фильтр по названию
    * limit - Количество строк на странице
    * offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 2,
            "items": [
                {
                    "id": 0,
                    "index": "sector_50_50", 
                    "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
                    "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
                    "_comment_program": "Массив позиций по УМ",
                    "program": {
                        "anglesArray": [
                            0,
                            0.791015625,
                            1.58203125,
                            2.373046875,
                            3.1640625,
                            4.04296875,
                            4.833984375,
                            5.625,
                            6.416015625,
                            7.20703125,
                            7.998046875,
                            8.7890625,
                            9.580078125,
                            10.37109375,
                            12.392578125,
                            14.4140625,
                            16.34765625,
                            34.453125,
                            37.44140625,
                            40.4296875,
                            43.41796875,
                            46.40625,
                            49.39453125
                        ],
                        "_comment_avAzimuthChange": "Azimuth at which the change of angle in the vertical",
                        "avAzimuthChange": 0,
                        "_comment_azimuthScanSpeed": "Speed scanning in azimuth",
                        "azimuthScanSpeed": 23.820384889522455,
                        "_comment_blankSectorsArray": "Массив секторов блокировки, всегда четный",
                        "blankSectorsArray": [
                            18.369140625,
                            20.390625,
                            22.412109375,
                            25.400390625,
                            28.388671875,
                            31.376953125,
                        ],
                        "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                        "mode": 5,
                        "_comment_rasterLeftAzimuth": "left border of a raster review",
                        "rasterLeftAzimuth": 15.029296875,
                        "_comment_rasterRightAzimuth": "right border of a raster review",
                        "rasterRightAzimuth": 74.970703125,
                        "_comment_scopeRange": "Current scope range",
                        "scopeRange": 50,
                        "date": "2018-01-30T17:25:52+00:00"
                    }
                },
                {
                    "id": 1,
                    "index": "sector_100_50",
                    "description": "Cканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 100 км",
                    "name": "СЕКТОР 100 км УМ 0-50° Аз45° шир. 60°",
                    "_comment_program": "Массив позиций по УМ",
                    "program": {
                        "anglesArray": [
                            0,
                            0.791015625,
                            1.58203125,
                            2.373046875,
                            3.1640625,
                            4.04296875,
                            4.833984375,
                            5.625,
                            6.416015625,
                            7.20703125,
                            7.998046875,
                            8.7890625,
                            9.580078125,
                            10.37109375,
                            12.392578125,
                            14.4140625,
                            16.34765625,
                            34.453125,
                            37.44140625,
                            40.4296875,
                            43.41796875,
                            46.40625,
                            49.39453125
                        ],
                        "_comment_avAzimuthChange": "Azimuth at which the change of angle in the vertical",
                        "avAzimuthChange": 0,
                        "_comment_azimuthScanSpeed": "Speed scanning in azimuth",
                        "azimuthScanSpeed": 23.820384889522455,
                        "_comment_blankSectorsArray": "Массив секторов блокировки, всегда четный",
                        "blankSectorsArray": [
                            18.369140625,
                            20.390625,
                            22.412109375,
                            25.400390625,
                            28.388671875,
                            31.376953125,
                        ],
                        "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                        "mode": 5,
                        "_comment_rasterLeftAzimuth": "left border of a raster review",
                        "rasterLeftAzimuth": 15.029296875,
                        "_comment_rasterRightAzimuth": "right border of a raster review",
                        "rasterRightAzimuth": 74.970703125,
                        "_comment_scopeRange": "Current scope range",
                        "scopeRange": 50,
                        "date": "2018-01-30T17:25:52+00:00"
                    }
                }
            ]
        }
        
## Программа [/program/{id}]

Работа с заданной программой (для всей АС СМРЛП)

+ Parameters
    + id (number) - ID программы

### Получить [GET]

+ Response 200 (application/json)

        {
            "id": 0,
            "index": "sector_50_50", 
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "anglesArray": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_avAzimuthChange": "Azimuth at which the change of angle in the vertical",
                "avAzimuthChange": 0,
                "_comment_azimuthScanSpeed": "Speed scanning in azimuth",
                "azimuthScanSpeed": 23.820384889522455,
                "_comment_blankSectorsArray": "Массив секторов блокировки, всегда четный",
                "blankSectorsArray": [
                    18.369140625,
                    20.390625,
                    22.412109375,
                    25.400390625,
                    28.388671875,
                    31.376953125,
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_rasterLeftAzimuth": "left border of a raster review",
                "rasterLeftAzimuth": 15.029296875,
                "_comment_rasterRightAzimuth": "right border of a raster review",
                "rasterRightAzimuth": 74.970703125,
                "_comment_scopeRange": "Current scope range",
                "scopeRange": 50,
                "date": "2018-01-30T17:25:52+00:00"
            }
        }

+ Response 404

### Удалить программу [DELETE]

+ Response 204

+ Response 409

        {
            "count": 2,
            "station_ids": [1,4]
        }
    
+ Response 404

### Создать программу [POST /program]

+ Request (application/json)

        {
            "id": 0,
            "index": "sector_50_50", 
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "anglesArray": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_avAzimuthChange": "Azimuth at which the change of angle in the vertical",
                "avAzimuthChange": 0,
                "_comment_azimuthScanSpeed": "Speed scanning in azimuth",
                "azimuthScanSpeed": 23.820384889522455,
                "_comment_blankSectorsArray": "Массив секторов блокировки, всегда четный",
                "blankSectorsArray": [
                    18.369140625,
                    20.390625,
                    22.412109375,
                    25.400390625,
                    28.388671875,
                    31.376953125,
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_rasterLeftAzimuth": "left border of a raster review",
                "rasterLeftAzimuth": 15.029296875,
                "_comment_rasterRightAzimuth": "right border of a raster review",
                "rasterRightAzimuth": 74.970703125,
                "_comment_scopeRange": "Current scope range",
                "scopeRange": 50,
                "date": "2018-01-30T17:25:52+00:00"
            }
        }

+ Response 422 (application/json)

    + Body

        {
            "id": 0,
            "index": "Невалидное значение",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "avAzimuthChange": "Невалидное значение",
                "azimuthScanSpeed": "Невалидное значение",
                "mode": "Невалидное значение",
                "rasterLeftAzimuth": "Невалидное значение",
                "rasterRightAzimuth": "Невалидное значение",
                "scopeRange": "Невалидное значение"
            }
        }

+ Response 201 (application/json)

### Обновить программу [PUT]

+ Request (application/json)

        {
            "id": 0,
            "index": "sector_50_50", 
            "description": "Сканирование пространства от 0 до 50° по углу места для получения детализированных данных о сдвигах ветра, турбулентности масштаба дальности 50 км",
            "name": "СЕКТОР 50 км УМ 0-50° Аз45° шир. 60°",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "anglesArray": [
                    0,
                    0.791015625,
                    1.58203125,
                    2.373046875,
                    3.1640625,
                    4.04296875,
                    4.833984375,
                    5.625,
                    6.416015625,
                    7.20703125,
                    7.998046875,
                    8.7890625,
                    9.580078125,
                    10.37109375,
                    12.392578125,
                    14.4140625,
                    16.34765625,
                    34.453125,
                    37.44140625,
                    40.4296875,
                    43.41796875,
                    46.40625,
                    49.39453125
                ],
                "_comment_avAzimuthChange": "Azimuth at which the change of angle in the vertical",
                "avAzimuthChange": 0,
                "_comment_azimuthScanSpeed": "Speed scanning in azimuth",
                "azimuthScanSpeed": 23.820384889522455,
                "_comment_blankSectorsArray": "Массив секторов блокировки, всегда четный",
                "blankSectorsArray": [
                    18.369140625,
                    20.390625,
                    22.412109375,
                    25.400390625,
                    28.388671875,
                    31.376953125,
                ],
                "_comment_mode": "Режим работы МРЛС (2 - Круговой Обзор ФМ, 3 - Растровый Обзов ФМ, 4 - Круговой Обзор, 5 - Растровый Обзор",
                "mode": 5,
                "_comment_rasterLeftAzimuth": "left border of a raster review",
                "rasterLeftAzimuth": 15.029296875,
                "_comment_rasterRightAzimuth": "right border of a raster review",
                "rasterRightAzimuth": 74.970703125,
                "_comment_scopeRange": "Current scope range",
                "scopeRange": 50,
                "date": "2018-01-30T17:25:52+00:00"
            }
        }

+ Response 200 (application/json)

+ Response 422 (application/json)

    + Body

        {
            "id": 0,
            "index": "Невалидное значение",
            "_comment_program": "Массив позиций по УМ",
            "program": {
                "avAzimuthChange": "Невалидное значение",
                "azimuthScanSpeed": "Невалидное значение",
                "mode": "Невалидное значение",
                "rasterLeftAzimuth": "Невалидное значение",
                "rasterRightAzimuth": "Невалидное значение",
                "scopeRange": "Невалидное значение"
            }
        }

+ Response 409

        {
            "count": 2,
            "station_ids": [1,4]
        }

+ Response 404    

## Журнал событий [/station_log/list{?type}{?station}{?from}{?to}{?message}{?limit}{?offset}]

Получение журнала событий заданного СМРЛП

### Получить список событий [GET]

+ Parameters
    * type - Тип события, информация или ошибка (error|info)
    * station - id СМРЛП
    * from - Начальный период поиска
    * to - Конечный период поиска
    * message - Сообщение
    * limit - Количество строк на странице
    * offset - Начиная с какой позиции выводить элементы

+ Response 200 (application/json)

        {
            "count": 4,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Превышен период обновления параметров калибровки."
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "error",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        },
                        "message": "Ошибка подключения к МРЛС. Проверьте настройки."
                    },
                    {
                        "id": 3,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Карта местных отражений очищена"
                    },
                    {
                        "id": 4,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 2,
                            "title": "Чкаловский"
                        },
                        "message": "Карта местных отражений очищена"
                    }
                ]
        }
        
## Уведомления [/alarm/list{?stations}]

Глобальный список уведомлений

### Получить список уведомлений [GET]

+ Parameters
    * stations - список id СМРЛП


+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "error",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        },
                        "message": "Ошибка соединения."
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "info",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        },
                        "message": "Слабый сигнал."
                    }
                ]
        }
        
## Опасные явления [/dangerous_meteo/list{?stations}]

Голобальный список обнаруденных опасных метеоявлений

### Получить список опасных явлений [GET]

+ Parameters
    * stations - список id СМРЛП


+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "id": 1,
                        "date": "2017-05-15T08:30:00",
                        "type": "Шторм",
                        "station": {
                            "id": 6,
                            "title": "Щелково"
                        }
                    },
                    {
                        "id": 2,
                        "date": "2017-05-15T08:30:00",
                        "type": "Сильный ливень",
                        "station": {
                            "id": 1,
                            "title": "Орловка"
                        }
                    }
                ]
        }

## Настройки экспорта BUFR [/settings/bufr]
 
Экспорт данных АС СМРЛП в заданные направления по протоколу FTP
 
### Получить список настроек экспорта BUFR [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "stations": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "stations": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }

### Обновить список настроек экспорта BUFR [PUT]

+ Request (application/json)

        [
            {
                "active": true,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "stations": [
                    {
                        "id": 1,
                        "title": "Орловка"
                    },
                    {
                        "id": 2,
                        "title": "Чкаловский"
                    },
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            },
            {
                "active": false,
                "ip": "40.72.241.112",
                "port": 21,
                "path": "/var/lib/monocle/data/",
                "stations": [
                    {
                        "id": 3,
                        "title": "Братск"
                    }
                ]
            }
        ]

+ Response 200 (application/json)

        {
            "count": 2,
            "items": 
                [
                    {
                        "active": true,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "stations": [
                            {
                                "id": 1,
                                "title": "Орловка"
                            },
                            {
                                "id": 2,
                                "title": "Чкаловский"
                            },
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    },
                    {
                        "active": false,
                        "ip": "40.72.241.112",
                        "port": 21,
                        "path": "/var/lib/monocle/data/",
                        "stations": [
                            {
                                "id": 3,
                                "title": "Братск"
                            }
                        ]
                    }
                ]
        }
    
+ Response 422 (application/json)

    + Body
            
            {
                "count": 1,
                "items": 
                    [
                        {
                            "index": 1,
                            "active": "Невалидное значение",
                            "ip": "Невалидное значение",
                            "port": "Невалидное значение",
                            "path": "Невалидное значение",
                            "stations": "Невалидное значение"
                        }
                    ]
            }

## Построение карт РЛП [/settings/rlp]
 
Настройки алгоритма построения карт РЛП

### Получить настройки для построения карт РЛП [GET]

+ Response 200 (application/json)

        {
            "velocityvectormap":
            {
                "arrowwidth": 2,
                "filterSMAOn": true,
                "_comment_horWSBuilderStep": "гор. шаг построения",
                "horWSBuilderStep": 500,
                "_comment_kLongRangeSizeOverlapH": "коэффицинент перекрытия для области построения вектора для большой дальности в гор. пл.",
                "kLongRangeSizeOverlapH": 3.75,
                "_comment_kLongRangeSizeOverlapV": "коэффицинент перекрытия для области построения вектора для большой дальности в верт. пл.",
                "kLongRangeSizeOverlapV": 2.0,
                "_comment_kMediumRangeSizeOverlapH": "коэффицинент перекрытия для области построения вектора для средней дальности в гор. пл.",
                "kMediumRangeSizeOverlapH": 3.25,
                "_comment_kMediumRangeSizeOverlapV": "коэффицинент перекрытия для области построения вектора для средней дальности в верт. пл.",
                "kMediumRangeSizeOverlapV": 1.75,
                "_comment_kShortRangeSizeOverlapH": "коэффицинент перекрытия для области построения вектора для малой дальности в гор. пл.",
                "kShortRangeSizeOverlapH": 2.0,
                "_comment_kShortRangeSizeOverlapV": "коэффицинент перекрытия для области построения вектора для малой дальности в верт. пл.",
                "kShortRangeSizeOverlapV": 1.5,
                "_comment_": "",
                "longRAzCellFillThreshold": 15,
                "longRAzCellThreshold": 17,
                "maxCircleWSAltitude": 3000,
                "maxCircleWSRange": 50000,
                "_comment_maxRastrWSAltitude": "максимальная высота расчета",
                "maxRastrWSAltitude": 3000,
                "_comment_maxRastrWSRange": "максимальная дальность расчета",
                "maxRastrWSRange": 50000,
                "mediumRAzCellFillThreshold": 17,
                "mediumRAzCellThreshold": 23,
                "shortRAzCellFillThreshold": 15,
                "shortRAzCellThreshold": 20,
                "sizearrowvvf": 30,
                "stepbuildhor": 8000,
                "stepbuildhorSector": 8000,
                "_comment_": "",
                "stepbuildvert": 1000,
                "stepbuildvertSector": 1000,
                "_comment_thresholdDeltaVelosity": "порог для определения валидности вектора по относительной погрешности",
                "thresholdDeltaVelosity": 0.0001,
                "_comment_thresholdEpcilonVelosity": "порог для определения валидности вектора по абсолютной погрешности",
                "thresholdEpcilonVelosity": 0.001,
                "_comment_verWSBuilderStep": "верт. шаг построения",
                "verWSBuilderStep": 500
            },
            "verticalsectionmap":
            {
                "automaxheight": 0,
                "maxheight": 7.5,
                "stepHBuildVSection": 100,
                "stepSBuildVSection": 100
            }
        }

### Обновить настройки для построения карт [PUT]

+ Request (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": 100,
                "circular_vertical_pitch": 100,
                "sector_horizontal_pitch": 100,
                "sector_vertical_pitch": 100
            },
            "wind_shear_field": {
                "circular_max_height": 100,
                "circular_max_distance": 100,
                "sector_max_height": 100,
                "sector_max_distance": 100,
                "horizontal_pitch": 100,
                "vertical_pitch": 100
            },
            "atmospheric_process": {
                "cell_size": 150,
                "line_generalization": 3,
                "line_expansion": 3,
            },
            "vector": {
                "size": 5,
                "thickness": 3
            },
            "vertical_section": {
                "horizontal_pitch": 100,
                "vertical_pitch": 100
            },
            "accumulated_precipitation": {
                "cell_size": 100
            },
            "vertically_integrated_liquid": {
                "cell_size": 100
            }
        }

+ Response 200 (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": 100,
                "circular_vertical_pitch": 100,
                "sector_horizontal_pitch": 100,
                "sector_vertical_pitch": 100
            },
            "wind_shear_field": {
                "circular_max_height": 100,
                "circular_max_distance": 100,
                "sector_max_height": 100,
                "sector_max_distance": 100,
                "horizontal_pitch": 100,
                "vertical_pitch": 100
            },
            "atmospheric_process": {
                "cell_size": 150,
                "line_generalization": 3,
                "line_expansion": 3,
            },
            "vector": {
                "size": 5,
                "thickness": 3
            },
            "vertical_section": {
                "horizontal_pitch": 100,
                "vertical_pitch": 100
            },
            "accumulated_precipitation": {
                "cell_size": 100
            },
            "vertically_integrated_liquid": {
                "cell_size": 100
            }
        }

+ Response 422 (application/json)

        {
            "vector_velocity_field": {
                "circular_horizontal_pitch": "Невалидное значение",,
                "circular_vertical_pitch": "Невалидное значение",,
                "sector_horizontal_pitch": "Невалидное значение",,
                "sector_vertical_pitch": "Невалидное значение",
            },
            "wind_shear_field": {
                "sector_max_distance": "Невалидное значение"
            },
            "vertically_integrated_liquid": {
                "cell_size": "Невалидное значение"
            }
        }

## Список настроек цветовых шкал [/settings/color_scale/list]

Цветовые шкалы - легенды при выводе продуктов

### Получить список настроек цветовых шкал [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "items":
            [
                {
                    "id": 1,
                    "title": "Отражаемость",
                    "count": 3,
                    "items":
                        [
                            {
                                "index": 1,
                                "value": 30,
                                "color": "#010178"
                            },
                            {
                                "index": 2,
                                "value": 35,
                                "color": "#fffb00"
                            },
                            {
                                "index": 3,
                                "value": 40,
                                "color": "#f500f6"
                            }
                        ]
                },
                {
                    "id": 2,
                    "title": "Радиальная скорость",
                    "count": 3,
                    "items":
                        [
                            {
                                "index": 1,
                                "value": 30,
                                "color": "#010178"
                            },
                            {
                                "index": 2,
                                "value": 35,
                                "color": "#fffb00"
                            },
                            {
                                "index": 3,
                                "value": 45,
                                "color": "#f500f6"
                            }
                        ]
                }
            ]        
        }

## Настройки цветовой шкалы [/settings/color_scale/{id}]

Редактирование цветовых шкал

+ Parameters
    + id (number) - ID раздела настроек цветовой шкалы

### Обновить настройки цветовой шкалы [PUT]

+ Request (application/json)

        {
            "count": 3,
            "items":
            [
                {
                    "index": 1,
                    "value": 30,
                    "color": "#010178"
                },
                {
                    "index": 2,
                    "value": 35,
                    "color": "#fffb00"
                },
                {
                    "index": 3,
                    "value": 40,
                    "color": "#f500f6"
                }
            ]
        }

+ Response 200 (application/json)

        {
            "count": 3,
            "items": 
            [
                {
                    "index": 1,
                    "value": 30,
                    "color": "#010178"
                },
                {
                    "index": 2,
                    "value": 35,
                    "color": "#fffb00"
                },
                {
                    "index": 3,
                    "value": 40,
                    "color": "#f500f6"
                }
            ]
        }
        
+ Response 422 (application/json)

        {
            "count": 1,
            "items": 
            [
                {
                    "index": 1,
                    "value": "Невалидное значение",
                    "color": "Невалидное значение"
                }
            ]
        }
        
+ Response 404

## Настройки цветовой шкалы по умолчанию [/settings/color_scale/{id}/default]

Всегда может понадобиться сбросить цветовую шкалу в состояние "по-умолчанию"

+ Parameters
    + id (number) - ID раздела настроек цветовой шкалы

### Получить настройки цветовой шкалы по умолчанию [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "count": 3,
            "title": "Радиальная скорость",
            "items":
            [
                {
                    "id": 1,
                    "value": 30,
                    "color": "#010178"
                },
                {
                    "id": 2,
                    "value": 35,
                    "color": "#fffb00"
                },
                {
                    "id": 3,
                    "value": 40,
                    "color": "#f500f6"
                }
            ]
        }

## Критерии классификации типов метеоявлений по-умолчанию [/settings/default_weather_criteria]

Типовой (зашитый производителем) перечень критериев классификации МЯ по фиксированному перечню параметров
Для редкатирования см. настроки отдельного СМРЛП - для каждого СМРЛП теоретически могут быть свои критерии

### Получить [GET]

+ Response 200 (application/json)

        {
            "count": 3,
            "items":
            [
                {
                    // Индекс МЯ
                    "id": 0, 
                    // Наименование МЯ
                    "type": "Облачность (слоистообразная облачность)",
                    "count": 1,
                    "items":
                    [
                    {
                        // Индекс параметра
                        "index": 0,
                        // Код параметра
                        "code": "Cl_dBZ23_min",
                        // Наименование параметра
                        "title": "Минимальное значение радиолокационной отражаемости на уровнях Z2 и Z3",
                        // Единицы измерения параметра
                        "measurement unit": "dBZ"
                        // Значение параметра для теплого периода
                        "warm": 10,
                        // Значение параметра для холодного периода
                        "cold": -10, 
                        // Код параметра
                        "service_life": "All" // (Warm, Cold, All)
                    }
                    ]
                },
                {
                    "id": 1, 
                    "type": "Облачность (кучевая облачность)",
                    "count": 1,
                    "items":
                    [
                    {
                        "index": 0,
                        "code": "Cl_dBZ2_min",
                        "title": "Минимальное значение радиолокационной отражаемости на уровне Z2",
                        "measurement unit": "dBZ"
                        "service_life": "All"
                    },
                    {
                        "index": 1,
                        "code": "Cl_dBZ3_min",
                        "title": "Минимальное значение радиолокационной отражаемости на уровнях Z3",
                        "measurement unit": "dBZ"
                        "warm": 35,
                        "cold": 30,
                        "service_life": "All"
                    }
                    ]
                }
            ]
        }

## Входные данные для алгоритма расчёта поправки на север [/north_calc{?id}]

Упрощение расчета поправки на север путем ввода данных ориентиров

+ Parameters
    + id (number) - ID СМРKП

### Установить [POST]

+ Request (application/json)

        {
            "distance_north": 200.0,
            "distance_north_install": 100.0,
            "distance_install": 300.3
        }

+ Response 200

+ Response 422 (application/json)

        {
            "distance_north": "Невалидное значение",
            "distance_north_install": "Невалидное значение",
            "distance_install": "Невалидное значение"
        }

## Вертикальное сечение [/vertical_section_by_route]

Предоставление вертикального сечения по маршруту для выбранного метеопродукта на заданном диапазоне высот.

### Получить [POST]

+ Request  (application/json)

        {
            "station_id": 1,
            "date": "2017-05-15T08:30:00",
            "route_points": [{
                "latitude": 55.807775,
                "longitude": 37.566814
            },
            {
                "latitude": 55.807775,
                "longitude": 37.566814
            }],
            "max_altitude": 5000.2,
            "rlp_type": 2
        }

+ Response 200

## Вертикальный профиль [/vertical_profile]

Предоставление вертикального профиля для выбранного метеопродукта на заданном диапазоне  высот

### Получить [POST]

+ Request  (application/json)

        {
            "station_id": 1,
            "date": "2017-05-15T08:30:00",
            "marker_pos": {
                "latitude": 55.807775,
                "longitude": 37.566814
            },
            "max_altitude": 5000.2,
            "rlp_type": 2
        }

+ Response 200

## Уведомления [/notification]

Поднимаем один вебсокет для общения с интерфейсом. В поле type указываем типа уведомления. Состав content'a зависит от типа

### Уведомление об окончании обработки очередного пакета данных

+ Request (application/json)

        {
            "type": "new_product",
            "content": {
                "station_id":0,
                "date": "2017-05-15T08:30:00"
            }
        }